# Generated by Django 5.2.1 on 2025-09-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('sci-fi', 'Sci-Fi'), ('biography', 'Biography'), ('poetry', 'Poetry'), ('philosophical', 'Philosophical'), ('allegory', 'Allegory'), ('self-help', 'Self-Help'), ('motivational', 'Motivational'), ('psychology', 'Psychology'), ('spirituality', 'Spirituality'), ('personal-development', 'Personal Development'), ('health-wellness', 'Health & Wellness'), ('business', 'Business & Finance'), ('leadership', 'Leadership'), ('productivity', 'Productivity'), ('history', 'History'), ('science', 'Science'), ('technology', 'Technology'), ('travel', 'Travel'), ('true-crime', 'True Crime'), ('adventure', 'Adventure'), ('thriller', 'Thriller'), ('drama', 'Drama'), ('classic', 'Classic Literature')], default='fiction', max_length=50),
        ),
    ]
