# Generated by Django 5.2.1 on 2025-08-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0003_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auther',
            new_name='author',
        ),
    ]
